---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

```{r}
mi = c(38.23, 38.23, 13.70, 0.75, 2.85, 2.00, 5.00, 10.80, 2.00, 8.81, 6.50, 15.00, 7.00, 16.00, 12.30, 3.86, 15.80, 9.00, 21.00, 21.00, 1.50, 8.00, 28.42, 9.01, 9.01, 0.75, 6.00, 28.43, 9.97, 6.20)
yi = c(10926, 10926, 1024, 13, 30, 1102, 600, 290, 430, 992, 1900, 864, 17, 1045, 220, 4600, 2370, 940, 640, 640, 10, 80, 13672, 3845, 3845, 480, 311, 9284, 842, 510)
```

$$
\hat Y_{HH} = \frac{1}{n}\sum\limits_{i=1}^n\frac{y_i}{Z_i}
$$

对于PPS抽样，$Z_i=M_i/M_0$

$$
\hat Y_{HH} = \frac{M_0}{n}\sum\limits_{i=1}^n\frac{y_i}{M_i}
$$

$$
V(\hat Y_{HH}) = \frac{1}{n}(\sum\limits_{i=1}^N\frac{Y_i^2}{Z_i}-Y^2)=\frac{1}{n}\sum\limits_{i=1}^NZ_i(\frac{Y_i}{Z_i}-Y)^2
$$

当$n>1$时，给出了$V(\hat Y_{HH})$的无偏估计
$$
v(\hat Y_{HH})=\frac{1}{n(n-1)}\sum\limits_{i=1}^n(\frac{y_i}{Z_i}-\hat Y_{HH})^2
$$

```{r}
n = 30
M0 = 3676
YHH.hat = sum(yi/mi)*M0/n
YHH.hat
```

$$
v(\hat Y_{HH})=\frac{M_0^2}{n(n-1)}\sum\limits_{i=1}^n(\frac{y_i}{m_i}-\frac{\hat Y_{HH}}{M_0})^2
$$

```{r}
YHH.var = M0^2/(n*(n-1))*sum((yi/mi-YHH.hat/M0)^2)
YHH.s = sqrt(YHH.var)
```

相对误差
```{r}
r = 1.96*YHH.s/YHH.hat
r
```
相对误差达到20\%时所需的样本量
```{r}
n = (r/0.2)^2*30
n
```